development:
  cloud_name: ENV["cloud_name"]
  api_key: ENV["api_key"]
  api_secret: ENV["api_secret"]
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ENV["cloud_name"]
  api_key: ENV["api_key"]
  api_secret: ENV["api_secret"]
  enhance_image_tag: true
  static_file_support: true